// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTNQLn7FzN6Gre-rmiIR2-Jx7-1yZlLw',
    appId: '1:347878142359:web:73c7858e5663012f6314d2',
    messagingSenderId: '347878142359',
    projectId: 'carelink-ed263',
    authDomain: 'carelink-ed263.firebaseapp.com',
    storageBucket: 'carelink-ed263.firebasestorage.app',
    measurementId: 'G-405PHP9J15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAINxNtPjacKy6MPIJsdvnUiUrE2yyA_Q',
    appId: '1:347878142359:android:a3c4fe73e41d11986314d2',
    messagingSenderId: '347878142359',
    projectId: 'carelink-ed263',
    storageBucket: 'carelink-ed263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_2GFwuajzO3w2lYf5eMbjd2vlwtSdhM',
    appId: '1:347878142359:ios:1e94d8641a2546d36314d2',
    messagingSenderId: '347878142359',
    projectId: 'carelink-ed263',
    storageBucket: 'carelink-ed263.firebasestorage.app',
    iosClientId: '347878142359-br46smgujpr0h6248d6pourf31otgh7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.carelinkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_2GFwuajzO3w2lYf5eMbjd2vlwtSdhM',
    appId: '1:347878142359:ios:1e94d8641a2546d36314d2',
    messagingSenderId: '347878142359',
    projectId: 'carelink-ed263',
    storageBucket: 'carelink-ed263.firebasestorage.app',
    iosClientId: '347878142359-br46smgujpr0h6248d6pourf31otgh7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.carelinkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvTNQLn7FzN6Gre-rmiIR2-Jx7-1yZlLw',
    appId: '1:347878142359:web:c8e3516fbe7dd55c6314d2',
    messagingSenderId: '347878142359',
    projectId: 'carelink-ed263',
    authDomain: 'carelink-ed263.firebaseapp.com',
    storageBucket: 'carelink-ed263.firebasestorage.app',
    measurementId: 'G-RYSFREQHZX',
  );

}